apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ mustMerge (dict "name" "loggregator-bridge") . | include "eirinix.component-name" }}
  labels:
    app.kubernetes.io/component: loggregator-bridge
{{ include "eirinix.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eirinix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: loggregator-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eirinix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: loggregator-bridge
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.service_account.name | quote }}
      initContainers:
        - name: generate-config
          image: mookas/eirini-loggregator-bridge-setup
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: NAMESPACE
            value: {{ .Values.namespace }}
          - name: LOGGREGATOR_ENDPOINT
            value: {{ .Values.loggregator.endpoint }}
          volumeMounts:
          - name: config
            mountPath: /run/secrets/config
      containers:
        - name: loggregator-bridge
          {{- with .Values.image }}
          image: {{ printf "%s/eirinix-loggregator-bridge:%s" .repository .tag | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ --config, /run/secrets/config/eirini-loggregator-bridge.yaml ]
          env:
          - name: EIRINI_LOGGREGATOR_BRIDGE_LOGLEVEL
            value: DEBUG
          volumeMounts:
          - name: config
            mountPath: /run/secrets/config
          - name: loggregator-ca
            mountPath: /run/secrets/loggregator-ca
          - name: loggregator-cert
            mountPath: /run/secrets/loggregator-cert
          resources:
            {{- index .Values.resources "loggregator-bridge" | toYaml | nindent 12 }}
      volumes:
      - name: config
        emptyDir: {}
      - name: loggregator-ca
        secret:
          secretName: {{ .Values.loggregator.secrets.ca }}
          items:
          - key: certificate
            path: certificate
      - name: loggregator-cert
        secret:
          secretName: {{ .Values.loggregator.secrets.cert }}
          items:
          - key: certificate
            path: certificate
          - key: private_key
            path: private_key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
