{{- $component := "persi-broker" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ mustMerge (dict "name" $component) . | include "eirinix.component-name" }}
  labels:
    app.kubernetes.io/component: {{ $component }}
{{ include "eirinix.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eirinix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eirinix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ $component }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.service_account.name | quote }}
      initContainers:
      - name: generate-config
        image: mookas/eirini-{{ $component }}-setup
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SERVICE_CONFIG
          value: |
            service:
            {{- with index .Values $component }}
              service_name: eirini-persi
              service_id: eirini-persi
              plans:
                {{- range index . "service-plans" }}
                - plan_id: {{ .id }}
                  plan_name: {{ .name }}
                  description: {{ .description }}
                  kube_storage_class: {{ .kube_storage_class }}
                  free: {{ .free }}
                  deault_size: {{ .default_size }}
                {{- end }}
              description: {{ .description }}
              long_description: {{ .long_description }}
              provider_display_name: {{ .provider_display_name }}
              documentation_url: {{ .documentation_url }}
              support_url: {{ .support_url }}
              display_name: {{ .display_name }}
              icon_image: {{ .icon_image }}
            {{- end }}
        - name: NAMESPACE
          value: {{ .Values.namespace }}
        volumeMounts:
        - name: config
          mountPath: /run/secrets/config
        - name: auth-password
          mountPath: /run/secrets/auth-password
      containers:
      - name: persi-broker
        {{- with .Values.image }}
        image: {{ printf "%s/eirinix-%s:%s" .repository $component .tag | quote }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: BROKER_CONFIG_PATH
          value: /run/secrets/config/eirini-persi-broker.yml
        volumeMounts:
        - name: config
          mountPath: /run/secrets/config
        resources:
          {{- index .Values.resources $component | toYaml | nindent 12 }}
      volumes:
      - name: config
        emptyDir: {}
      - name: auth-password
        secret:
          secretName: {{ index .Values $component "secrets" "auth-password" }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: eirini-persi-broker
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    quarks.cloudfoundry.org/instance-group-name: eirini
    quarks.cloudfoundry.org/deployment-name: {{ index .Values "deployment-name" }}
  ports:
  - protocol: TCP
    name: http
    port: 8999
    targetPort: 8999
