apiVersion: v1
kind: Service
metadata:
  name: {{ include "eirinix.fullname" . }}
  labels:
{{ include "eirinix.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "eirinix.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
