{{- $component := "ssh" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ mustMerge (dict "name" $component) . | include "eirinix.component-name" }}
  labels:
    app.kubernetes.io/component: {{ $component }}
{{ include "eirinix.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eirinix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eirinix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ $component }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.service_account.name | quote }}
      containers:
      - name: {{ $component }}
        {{- with .Values.image }}
        image: {{ printf "%s/eirinix-%s:%s" .repository $component .tag | quote}}
        {{- end }}
        command: [ /{{ $component }} ]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: EIRINI_EXTENSION_HOST
          value: "0.0.0.0"
        - name: EIRINI_EXTENSION_PORT
          value: "2999"
        - name: EIRINI_EXTENSION_NAMESPACE
          value: {{ .Values.namespace }}
        - name: OPERATOR_SERVICE_NAME
          value: eirini-ssh
        - name: OPERATOR_WEBHOOK_NAMESPACE
          value: {{ .Release.Namespace }}
        resources:
          {{- index .Values.resources $component | toYaml | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: eirini-{{ $component }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    quarks.cloudfoundry.org/instance-group-name: eirini
    quarks.cloudfoundry.org/deployment-name: {{ index .Values "deployment-name" }}
  ports:
  - protocol: TCP
    name: https
    port: 443
    targetPort: 2999
